name: Project Build and Test
inputs:
  preset:
    description: 'The CMake preset to be built'
    required: true
  shell:
    description: 'The shell executable that runs the script'
    required: true
  coverage:
    description: 'Whether to run coverage analysis'
    required: false
    default: false
  gconv_config_file:
    description: 'The gconv configuration file'
    required: false
    default: 'gconv.cfg'

env:
  COVERAGE_ENABLED: ${{ inputs.coverage && runner.os == 'Linux' }}
  BUILD_DIR: "out/build/${{ inputs.preset }}"
  
runs:
  using: "composite"
  steps:
    - name: Configure coverage flags on Linux build
      if: ${{ env.COVERAGE_ENABLED }}
      shell: ${{ inputs.shell }}
      run: |
        export CXXFLAGS='--coverage -O0'
        export LDFLAGS='--coverage -O0'
    - name: Run CMake
      shell: ${{ inputs.shell }}
      run: |
        cmake --preset ${{ inputs.preset }}
        cmake --build ${{ env.BUILD_DIR }}
        cmake --build ${{ env.BUILD_DIR }} --target install
    - name: Run Test
      shell: ${{ inputs.shell }}
      run: |
        cd ${{ env.BUILD_DIR }}
        ctest --output-on-failure
    - name: Generate coverage report
      if: ${{ env.COVERAGE_ENABLED }}
      shell: ${{ inputs.shell }}
      run: |
        gcovr --config "${{ inputs.gconv_config_file }}" --exclude-unreachable-branches --exclude-throw-branches --coveralls --output "${{ env.BUILD_DIR }}/coverage.json"
    - name: Upload coverage to Coveralls
      if: ${{ env.COVERAGE_ENABLED }}
      uses: coverallsapp/github-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        file: "${{ env.BUILD_DIR }}/coverage.json"
